# Generated by Django 4.0 on 2021-12-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotacao',
            old_name='data',
            new_name='data_final',
        ),
        migrations.AddField(
            model_name='cotacao',
            name='data_inicial',
            field=models.DateField(blank=True, null=True),
        ),
    ]
