# Generated by Django 3.1.1 on 2021-12-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_data_cotacao_data_final_cotacao_data_inicial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotacao',
            options={'verbose_name': 'Cotações', 'verbose_name_plural': 'Cotacoes'},
        ),
        migrations.AlterModelOptions(
            name='moedas',
            options={'verbose_name': 'Moeda', 'verbose_name_plural': 'Moedas'},
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='moedas',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='cotacao',
            table='cotacoes',
        ),
        migrations.AlterModelTable(
            name='moedas',
            table='moedas',
        ),
    ]
