# Generated by Django 3.1.1 on 2021-12-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211226_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='moeda',
            field=models.CharField(choices=[('BRL', 'Real'), ('EUR', 'Euro'), ('JPY', 'Iene')], default='BRL', max_length=15),
        ),
        migrations.DeleteModel(
            name='Moedas',
        ),
    ]
