# Generated by Django 3.1.1 on 2021-12-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211227_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
