# Generated by Django 3.1.1 on 2021-12-31 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cotacao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='data_cotacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
