# Generated by Django 4.0 on 2022-01-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cotacao_data_cotacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
