# Generated by Django 4.0 on 2022-01-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220101_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
